/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Min extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Min\",\"namespace\":\"models\",\"fields\":[{\"name\":\"f\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public boolean f;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Min() {}

  /**
   * All-args constructor.
   */
  public Min(java.lang.Boolean f) {
    this.f = f;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return f;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: f = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f' field.
   */
  public java.lang.Boolean getF() {
    return f;
  }

  /**
   * Sets the value of the 'f' field.
   * @param value the value to set.
   */
  public void setF(java.lang.Boolean value) {
    this.f = value;
  }

  /** Creates a new Min RecordBuilder */
  public static models.Min.Builder newBuilder() {
    return new models.Min.Builder();
  }
  
  /** Creates a new Min RecordBuilder by copying an existing Builder */
  public static models.Min.Builder newBuilder(models.Min.Builder other) {
    return new models.Min.Builder(other);
  }
  
  /** Creates a new Min RecordBuilder by copying an existing Min instance */
  public static models.Min.Builder newBuilder(models.Min other) {
    return new models.Min.Builder(other);
  }
  
  /**
   * RecordBuilder for Min instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Min>
    implements org.apache.avro.data.RecordBuilder<Min> {

    private boolean f;

    /** Creates a new Builder */
    private Builder() {
      super(models.Min.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(models.Min.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f)) {
        this.f = data().deepCopy(fields()[0].schema(), other.f);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Min instance */
    private Builder(models.Min other) {
            super(models.Min.SCHEMA$);
      if (isValidValue(fields()[0], other.f)) {
        this.f = data().deepCopy(fields()[0].schema(), other.f);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'f' field */
    public java.lang.Boolean getF() {
      return f;
    }
    
    /** Sets the value of the 'f' field */
    public models.Min.Builder setF(boolean value) {
      validate(fields()[0], value);
      this.f = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'f' field has been set */
    public boolean hasF() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'f' field */
    public models.Min.Builder clearF() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Min build() {
      try {
        Min record = new Min();
        record.f = fieldSetFlags()[0] ? this.f : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
