/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package models;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Min extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4892124173000986143L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Min\",\"namespace\":\"models\",\"fields\":[{\"name\":\"f\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Min> ENCODER =
      new BinaryMessageEncoder<Min>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Min> DECODER =
      new BinaryMessageDecoder<Min>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Min> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Min> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Min>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Min to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Min from a ByteBuffer. */
  public static Min fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public boolean f;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Min() {}

  /**
   * All-args constructor.
   * @param f The new value for f
   */
  public Min(java.lang.Boolean f) {
    this.f = f;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return f;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: f = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f' field.
   * @return The value of the 'f' field.
   */
  public java.lang.Boolean getF() {
    return f;
  }

  /**
   * Sets the value of the 'f' field.
   * @param value the value to set.
   */
  public void setF(java.lang.Boolean value) {
    this.f = value;
  }

  /**
   * Creates a new Min RecordBuilder.
   * @return A new Min RecordBuilder
   */
  public static models.Min.Builder newBuilder() {
    return new models.Min.Builder();
  }

  /**
   * Creates a new Min RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Min RecordBuilder
   */
  public static models.Min.Builder newBuilder(models.Min.Builder other) {
    return new models.Min.Builder(other);
  }

  /**
   * Creates a new Min RecordBuilder by copying an existing Min instance.
   * @param other The existing instance to copy.
   * @return A new Min RecordBuilder
   */
  public static models.Min.Builder newBuilder(models.Min other) {
    return new models.Min.Builder(other);
  }

  /**
   * RecordBuilder for Min instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Min>
    implements org.apache.avro.data.RecordBuilder<Min> {

    private boolean f;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(models.Min.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f)) {
        this.f = data().deepCopy(fields()[0].schema(), other.f);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Min instance
     * @param other The existing instance to copy.
     */
    private Builder(models.Min other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.f)) {
        this.f = data().deepCopy(fields()[0].schema(), other.f);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'f' field.
      * @return The value.
      */
    public java.lang.Boolean getF() {
      return f;
    }

    /**
      * Sets the value of the 'f' field.
      * @param value The value of 'f'.
      * @return This builder.
      */
    public models.Min.Builder setF(boolean value) {
      validate(fields()[0], value);
      this.f = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'f' field has been set.
      * @return True if the 'f' field has been set, false otherwise.
      */
    public boolean hasF() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'f' field.
      * @return This builder.
      */
    public models.Min.Builder clearF() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Min build() {
      try {
        Min record = new Min();
        record.f = fieldSetFlags()[0] ? this.f : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Min>
    WRITER$ = (org.apache.avro.io.DatumWriter<Min>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Min>
    READER$ = (org.apache.avro.io.DatumReader<Min>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
